import type { Metadata } from "next";
import "./globals.css";
import '../styles/animations.css';
import { Josefin_Sans } from "next/font/google";
import { ThemeProvider } from '@mui/material/styles';
import { theme } from "@/utils/theme";
import { UserProvider } from '@auth0/nextjs-auth0/client';

const josefin = Josefin_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${josefin.className} overflow-hidden`}>
        <UserProvider>
          <ThemeProvider theme={theme}>
            {children}
          </ThemeProvider>
        </UserProvider>
      </body>
    </html>
  );
}
