import type { Metadata } from "next";
import "./globals.css";
import { NextAuthProvider } from "./nextAuthProvider";
import { Josefin_Sans } from "next/font/google";
const josefin = Josefin_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${josefin.className}`}>
        <NextAuthProvider children={children} />
      </body>
    </html>
  );
}
